server:
  port: ${BIGSCREEN_BFF_PORT:8090}

center:
  manage-base-url: ${CENTER_MANAGE_BASE_URL:http://localhost:8088}
  control-base-url: ${CENTER_CONTROL_BASE_URL:http://localhost:8088}
  media-base-url: ${CENTER_MEDIA_BASE_URL:http://localhost:8088}
  websocket-control-url: ${CENTER_CONTROL_WS_URL:ws://localhost:8088/ws/control}

spring:
  application:
    name: bigscreen-bff
